version: '2'
services:
 web:
   image: vulhub/phpmyadmin:4.8.1
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "2345:80"
   links:
    - mysql:mysql
 mysql:
   image: mysql:5.5
   environment: 
    - MYSQL_ROOT_PASSWORD=toor
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
