FROM ubuntu:16.04



RUN apt-get update && apt-get -y install apache2 software-properties-common



RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php



RUN apt-get update && apt-get install -y libapache2-mod-php7.0 php7.0 php7.0-cli php7.0-mysql 



RUN a2enmod rewrite



COPY conf/000-default.conf /etc/apache2/sites-available/000-default.conf



COPY conf/dir.conf /etc/apache2/mods-available/dir.conf



COPY code/index.php /var/www/html/index.php

COPY code/login.php /var/www/html/login.php

COPY code/file.php /var/www/html/file.php

COPY code/write.php /var/www/html/write.php

COPY code/view.php /var/www/html/view.php

COPY code/download.php /var/www/html/download.php



EXPOSE 80



CMD apachectl -D FOREGROUND
